#macro(showexception $exc)

#end
<div id="container" class="fluid">
	<h2>Everything was good, then this happened:</h2>
	<h1>Unexpected error</h1>
	<p>Don't worry, we have a team of cougars tracking it down.<a href="#" id="show_hide_error"></a></p>
	<div style="margin-left:15px;" id="report_area_details"> 
 
        <h3>$exception.GetType().Name</h3>
    
        <h4>Message:</h4>
        <p>$exception.Message</p>
    
        #if($exception.StackTrace)
            <h4>StackTrace:</h4>
            <code style="font-size: 12px; line-height: 12px; display: inline-block;"> $exception.StackTrace </code>
        #end
    
        #if($exception.InnerException)
            <div style="margin-left:15px;">
                <h5>Inner exception:</h5>
                #set($inner = $exception.InnerException)
                <h3>$inner.GetType().Name</h3>
            
                <h4>Message:</h4>
                <p>$inner.Message</p>
            
                #if($inner.StackTrace)
                <h4>StackTrace:</h4>
                <code style="font-size: 12px; line-height: 12px; display: inline-block;"> $inner.StackTrace </code>
                #end
            </div>
        #end
        
        
    </div>
	<h2>Get Help:</h2>
	<a href="#" class="errorReporting">Contact support</a>
	</br>
	<img src="/Content/images/error/butch.png" width="451" style="max-width:451px;" height="558" alt="Butch leads the way!" id="butch" class="fluid"/>
	<a href="#" alt="Washington State University" id="get_back" onClick="window.history.go(-1);">Go back one step.</a>
</div>
